import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        justifyContent:"center",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        textAlign:"center",
        letterSpacing:1,
        color:"#FF9D0B",
    },
    scrollView:{
        paddingHorizontal:"12@ms",
        paddingVertical:"24@vs"
    },
    information:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms"
    },
    image:{
        width:"96@ms",
        height:"96@ms",
        borderRadius:"48@ms",
        backgroundColor:"gray",
        marginLeft:"12@ms"
    },
    viewText:{
        justifyContent:"center",
        marginLeft:"24@ms"
    },
    textName:{
        fontSize:20,
        fontWeight:"bold",
        textAlign:"center"
    },
    textType:{
        fontSize:20,
        color:"gray",
        textAlign:"center"
    },
    button:{
        backgroundColor:"white",
        borderRadius:"16@ms",
        padding:"12@ms",
        marginTop:"24@vs"
    },
    textButton:{
        fontSize:16,
        fontWeight:"bold",
        textAlign:"center"
    }
})