import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        letterSpacing:1,
        color:"#FF9D0B",
        marginLeft:"100@ms"
    },
    searchIcon:{
        marginLeft:"72@ms",
        marginTop:"4@vs"
    },
    shopIcon:{
        marginLeft:"8@ms",
        marginTop:"4@vs"
    },
    scrollView:{
        paddingHorizontal:"12@ms",
        paddingVertical:"24@vs",
        height:"80%"
    },
    viewCategory:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        
    },
    categories:{
        fontSize:16,
        fontWeight:"bold",
        color:"#FF9D0B"
    },
    listCategories:{
        flexDirection:"row",
        flexWrap:"wrap",
        justifyContent:"space-evenly"
    },
    button:{
        borderWidth:1,
        borderRadius:"8@ms",
        borderColor:"gray",
        padding:"14@ms",
        marginTop:"12@vs",
        marginLeft:"16@ms"
    },
    categoryName:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center"
    },
    image:{
        width:"96@ms",
        height:"96@ms",  
    },
    buttonAdd:{
        borderRadius:"12@ms",
        paddingHorizontal:"12@ms",
        backgroundColor:"green",
    },
    price:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"#FF9D0B",
    },
    location:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"gray",
    },
    bottombutton:{
        flexDirection:"row", 
        justifyContent:"space-between",
        marginTop:"12@vs"
    },
    cancelbutton:{
        backgroundColor:"red",
        width:"40%",
        height:"36@vs",
        borderRadius:"20@vs",
        alignItems:"center",
        justifyContent:"center"
    },
    addbutton:{
        backgroundColor:"#FF9D0B",
        width:"40%",
        height:"36@vs",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:"20@vs",
    },
    cancel:{
        color:"white",
        fontSize:16
    },
    add:{
        color:"white",
        fontSize:16
    },
})