import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        letterSpacing:1,
        color:"#FF9D0B",
        marginLeft:"96@ms"
    },
    shopIcon:{
        marginLeft:"80@ms",
        marginTop:"4@vs",
    },
    SearchContainer:{
        backgroundColor:"white",
        marginTop:"8@vs",
        borderTopWidth:0,
        borderBottomWidth:0,  
    },
    inputContainer:{
        backgroundColor:"#DCDCDC",
        borderRadius:"8@ms",
        borderWidth:1,
        borderBottomWidth:1,
        marginHorizontal:"8@ms"
    },
    input:{
       
    },
    viewCategory:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginHorizontal:"8@ms"
        
    },
    categoryName:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center"
    },
    image:{
        width:"96@ms",
        height:"96@ms",  
    },
    price:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"#FF9D0B",
    },
    location:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"gray",
    },
    filterIcon:{
        marginTop:"12@vs"
    },
    picker:{
        width:"50%",
        height:"80%",
        borderWidth:1,
        borderRadius:"8@vs",
        borderColor:"gray",
        marginLeft:"80@ms",
    },
    pickerItem:{
        color:"black", 
        width:"100%",
    }
})