import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        letterSpacing:1,
        color:"#FF9D0B",
        marginLeft:"44@ms"
    },
    scrollView:{
        paddingHorizontal:"12@ms",
        paddingVertical:"24@vs",
        height:"80%"
    },
    viewCategory:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginBottom:"8@ms"
    },
    categories:{
        fontSize:16,
        fontWeight:"bold",
        color:"black"
    },
    listProduct:{
        fontSize:16,
        fontWeight:"bold",
        color:"#FF9D0B"
    },
    listCategories:{
        flexDirection:"row",
        flexWrap:"wrap",
        justifyContent:"space-evenly"
    },
    button:{
        borderWidth:1,
        borderRadius:"8@ms",
        borderColor:"gray",
        padding:"12@ms",
        width:"140@vs",
        height:"112@vs",
        marginTop:"24@vs"
    },
    categoryName:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center"
    },
    image:{
        width:"96@ms",
        height:"96@ms",  
    },
    location:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"gray",
    },
    price:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"#FF9D0B",
    },

    delivery:{
        flexWrap:"wrap",
        fontSize:18,
        fontWeight:"bold",
        color:"#FF9D0B",
    },
    bottomView:{
        backgroundColor:"white",
        paddingVertical:"8@vs",
        borderWidth:1,
        borderRadius:"8@ms",
        borderColor:"#FF9D0B",
        marginHorizontal:"10@ms",
        marginVertical:"8@ms"
    },
    direct:{
        flexDirection:"row",
        marginLeft:"12@ms"
        
    },
    directText:{
      alignSelf:"center",
      flexWrap:"wrap",
      fontSize:16,
      fontWeight:"bold",   
    },
    Total:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        marginLeft:"12@ms"
    },
    
    buttonCart:{
        justifyContent:"center",
        backgroundColor:"red",
        alignItems:"center",
        marginHorizontal:"10@ms",
        borderRadius:"8@ms",
        paddingVertical:"8@vs"
    },
    textCart:{
        color:"white",
        fontSize:20,
        fontWeight:"bold"
    },
})