import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        letterSpacing:1,
        color:"#FF9D0B",
        marginLeft:"48@ms"
    },
    searchIcon:{
        marginLeft:"24@ms",
        marginTop:"4@vs"
    },
    shopIcon:{
        marginLeft:"8@ms",
        marginTop:"4@vs"
    },
    scrollView:{
        paddingHorizontal:"12@ms",
        paddingVertical:"24@vs",
        height:"80%"
    },
    image:{
        width:"164@ms",
        height:"164@ms",
        alignSelf:"center"  
    },
    viewCategory:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",   
    },
    viewProduct:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginTop:"16@vs"   
    },
    productName:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center"
    },
    price:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"#FF9D0B",
    },
    imageShop:{
        width:"96@ms",
        height:"96@ms",
        borderRadius:"48@ms",
        backgroundColor:"gray",
    },
    viewText:{
        justifyContent:"center",
        marginLeft:"16@ms"
    },
    textName:{
        fontSize:16,
        fontWeight:"bold",
        textAlign:"center"
    },
    location:{
        flexWrap:"wrap",
        fontSize:14,
        fontWeight:"bold",
        alignSelf:"center",
        color:"gray",
    },
    buttonShop:{
        borderWidth:1,
        borderColor:"#FF9D0B",
        justifyContent:"center",
        height:"30%",
        padding:"4@ms",
        borderRadius:"16@ms"
    },
    textShop:{
        textAlign:"center",
        fontSize:14,
        color:"#FF9D0B"
    },
    viewDecription:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginTop:"16@vs",
        marginBottom:"36@vs"
    },
    buttonCart:{
        justifyContent:"center",
        backgroundColor:"green",
        alignItems:"center",
        marginHorizontal:"10@ms",
        borderRadius:"8@ms",
        paddingVertical:"4@vs"
    },
    textCart:{
        color:"white",
        fontSize:16,
        fontWeight:"bold"
    },
    alert:{
        borderBottomLeftRadius:"52@ms",
        borderTopRightRadius:"52@ms"
    },
    alertTitle:{},
    alertMessage:{
        color:"black",
        fontSize:16,
        marginLeft:"14@ms",
        marginTop:"8@vs"
    },
    alertButton:{
        marginLeft:"160@ms",
        paddingHorizontal:"16@ms",
        paddingVertical:"4@vs",
        borderRadius:"16@ms",
    },
    confirmButtonText:{
        fontSize:14,
        color:"white"
    },
})