import React from 'react'
import {createStackNavigator} from '@react-navigation/stack'
import {NavigationContainer} from '@react-navigation/native'
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs'
import {Screens} from '../screen'
import {Router} from './route'
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons'
import Ionicons from 'react-native-vector-icons/Ionicons'

const {
    Splash,
    Login,
    Register,
    Home,
    OrderNow,
    Notification,
    Profile,
    ProductManager,
    ManagerDetail,
    AddProduct,
    EditProduct,
    MyOrder,
    OrderDetail,
    ChangeInformation,
    CategoryDetail,
    ProductDetail,
    ShopDetail,
    Search,
    SearchShop,
    CheckOut,
    Cart,
    AddOrder,
    OrderNow_Store,
    MyOrder_Cus,
    MyProduct,
    MyOrder_CusDetail
}=Screens
const Stack = createStackNavigator();
const MaterialBottomTabs=createMaterialBottomTabNavigator()
const Auth=()=>
    <Stack.Navigator
        initialRouteName={Router.Login}>
        <Stack.Screen
            name={Router.Login}
            component={Login}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.Register}
            component={Register}
            options={{
                headerShown:false
            }}
        />
    </Stack.Navigator>
const Profile_Nav=()=>
    <Stack.Navigator>
        <Stack.Screen
            name={Router.Profile}
            component={Profile}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.ProductManager}
            component={ProductManager}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.ManagerDetail}
            component={ManagerDetail}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.AddProduct}
            component={AddProduct}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.EditProduct}
            component={EditProduct}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.MyOrder}
            component={MyOrder}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.OrderDetail}
            component={OrderDetail}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.ChangeInformation}
            component={ChangeInformation}
            options={{
                headerShown:false
            }}
        />
    </Stack.Navigator>
const Home_Nav=()=>
    <Stack.Navigator>
        <Stack.Screen
            name={Router.Home}
            component={Home}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.CategoryDetail}
            component={CategoryDetail}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.ProductDetail}
            component={ProductDetail}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.ShopDetail}
            component={ShopDetail}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.Search}
            component={Search}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.SearchShop}
            component={SearchShop}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.CheckOut}
            component={CheckOut}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.Cart}
            component={Cart}
            options={{
                headerShown:false
            }}
        />
    </Stack.Navigator>
const Order_Nav=()=>
    <Stack.Navigator>
        <Stack.Screen
            name={Router.OrderNow}
            component={OrderNow}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.AddOrder}
            component={AddOrder}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.OrderNow_Store}
            component={OrderNow_Store}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.MyProduct}
            component={MyProduct}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.MyOrder_Cus}
            component={MyOrder_Cus}
            options={{
                headerShown:false
            }}
        />
        <Stack.Screen
            name={Router.MyOrder_CusDetail}
            component={MyOrder_CusDetail}
            options={{
                headerShown:false
            }}
        />
    </Stack.Navigator>
const BottomTabs=()=>
    <MaterialBottomTabs.Navigator
        activeColor='#FFBC01'
        barStyle={{
            backgroundColor:"#f0f8ff",
            borderRadius:8,
        }}
        
    >
        <MaterialBottomTabs.Screen
            name={"Home_Nav"}
            children={Home_Nav}
            options={{
                tabBarLabel:"Home",
                tabBarIcon:({focused})=> 
                    <FontAwesome 
                        name="home" 
                        focused={focused}
                        size={20} 
                        color={focused?"#FFBC01":"#636363"} 
                    />
            }}
        />
        <MaterialBottomTabs.Screen
            name={"Order_Nav"}
            children={Order_Nav}
            options={{
                tabBarLabel:"OrderNow",
                tabBarIcon:({focused})=> 
                    <FontAwesome 
                        name="flash" 
                        focused={focused}
                        size={20} 
                        color={focused?"#FFBC01":"#636363"} 
                    />
            }}
        />
        {/* <MaterialBottomTabs.Screen
            name={Router.Notification}
            component={Notification}
            options={{
                tabBarLabel:"Notification",
                tabBarIcon:({focused})=> 
                    <Ionicons
                        name="notifications" 
                        focused={focused}
                        size={20} 
                        color={focused?"#FFBC01":"#636363"} 
                    />
                
            }}
        /> */}
        <MaterialBottomTabs.Screen
            name={"Profile_Nav"}
            children={Profile_Nav}
            options={{
                tabBarLabel:"Profile",
                tabBarIcon:({focused})=> 
                    <MaterialIcons
                        name="person" 
                        focused={focused}
                        size={20} 
                        color={focused?"#FFBC01":"#636363"} 
                    />
            }}
        />
    </MaterialBottomTabs.Navigator> 
const AppNavigator=()=>{
    return(
        <NavigationContainer>
            <Stack.Navigator>
                <Stack.Screen
                    name={Router.Splash}
                    component={Splash}
                    options={{
                        headerShown:false
                    }}
                />
                <Stack.Screen
                    name={Router.Auth}
                    children={Auth}
                    options={{
                        headerShown:false
                    }}
                />
                <Stack.Screen
                    name={Router.BottomTabs}
                    children={BottomTabs}
                    options={{
                        headerShown:false
                    }}
                />
            </Stack.Navigator>
        </NavigationContainer>
    )
}
export default AppNavigator;