import {ScaledSheet} from "react-native-size-matters";

export default styles=ScaledSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f2f2f2",
    },
    header:{
        flexDirection:"row",
        backgroundColor:"white",
        padding:"12@ms"
    },
    textHeader:{
        fontSize:24,
        fontWeight:"600",
        letterSpacing:1,
        color:"#FF9D0B",
        marginLeft:"56@ms"
    },
    scrollView:{
        paddingHorizontal:"12@ms",
        paddingVertical:"24@vs",
        height:"80%"
    },
    viewCategory:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginBottom:"16@vs" 
    },
    categories:{
        fontSize:16,
        fontWeight:"bold",
        color:"#FF9D0B",
        alignSelf:"center"
    },
    viewProduct:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
        marginBottom:"32@vs"
    },
    image:{
        width:"96@ms",
        height:"96@ms",  
    },
    categoryName:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center"
    },
    price:{
        flexWrap:"wrap",
        fontSize:16,
        fontWeight:"bold",
        alignSelf:"center",
        color:"#FF9D0B",
    },
    viewQuanity:{
        flexDirection:"row"
    },
    textQuanity:{
        borderWidth:1,
        paddingHorizontal:"12@ms",
        marginLeft:"4@ms",
        marginTop:"4@vs"
    },
    viewbottom:{
        flexDirection:"row",
        backgroundColor:"white",
        marginHorizontal:"12@ms",
        paddingHorizontal:"8@ms",
        borderTopWidth:1,
        borderColor:"gray"
    },
    buttoncheckout:{
        backgroundColor:"green",
        paddingHorizontal:"16@ms",
        paddingVertical:"16@vs",
        marginLeft:"81@ms"
    },
    textCheckOut:{
        color:"white",
        fontSize:16,
        fontWeight:"bold"
    },


    searchIcon:{
        marginLeft:"72@ms",
        marginTop:"4@vs"
    },
    shopIcon:{
        marginLeft:"8@ms",
        marginTop:"4@vs"
    },
    viewShop:{
        backgroundColor:"white",
        borderRadius:"8@ms",
        padding:"12@ms",
    },
    imageShop:{
        width:"72@ms",
        height:"72@ms",
        borderRadius:"36@ms",
        backgroundColor:"gray",
        marginLeft:"16@ms"
    },
    viewText:{
        justifyContent:"center",
        marginLeft:"48@ms",
    },
    textName:{
        fontSize:16,
        fontWeight:"bold",
        textAlign:"center"
    },
    phoneIcon:{
        marginTop:"4@vs"
    },
    location:{
        flexWrap:"wrap",
        fontSize:14,
        fontWeight:"bold",
        alignSelf:"center",
        color:"gray",
    },
 
    delivery:{
        flexWrap:"wrap",
        fontSize:18,
        fontWeight:"bold",
    },
   
    direct:{
        flexDirection:"row",
        
    },
    directText:{
      alignSelf:"center",
      flexWrap:"wrap",
      fontSize:16,
      fontWeight:"bold",   
    },
    label:{
        fontSize:16,
        color:"black",
        fontWeight:"bold",
    },
    alert:{
        borderBottomLeftRadius:"52@ms",
        borderTopRightRadius:"52@ms"
    },
    alertTitle:{},
    alertMessage:{
        color:"black",
        fontSize:16,
        marginLeft:"14@ms",
        marginTop:"8@vs"
    },
    alertButton:{
        marginLeft:"160@ms",
        paddingHorizontal:"16@ms",
        paddingVertical:"4@vs",
        borderRadius:"16@ms",
    },
    confirmButtonText:{
        fontSize:14,
        color:"white"
    },
})